#server
server:
  port: 10000


#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: baby
    password: 1234

  #jpa
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      #jpa ddl-auto
      #create: DROP 후 CREATE
      #create-drop: DROP 후 CREATE 후 DROP, DML을 사용하지 않는 다면 DROP되지 않음
      #update: Entity와 DB 스키마 비교 후 수정 사항 반영(컬럼 추가)
      #validate: Entity와 DB 스키마 비교(다르면 예외 발생)
      ddl-auto: update

    #jpa format
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  #log
  output:
    ansi:
      enabled: always


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: heykiddoruready@gmail.com
    password: pfcsrjhmfmwhksym
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  #OAuth2
  security:
    oauth2:
      client:
        registration:
          #naver
          naver:
            client-name: Naver
            client-id: mmwkeUCk_aGZ5CRwz2zI
            client-secret: hhahl19XKJ
            redirect-uri: http://localhost:10000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,mobile,nickname

          #kakao
          kakao:
            client-id: 0c8cc08d9f8f4ef0430dfbdb6bb7b2c7
            client-secret: Zj7d2o5LVvPHy9JT8C8WyfPIF6kqD8MR
            redirect-uri: http://localhost:10000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email
            client_name: kakao

        provider:
          #naver
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          #kakao
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

